# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.getDeviceProps <- function(id) {
    .Call(`_barracuda_getDeviceProps`, id)
}

.cuBLASdgemm <- function(A, B) {
    .Call(`_barracuda_cuBLASdgemm`, A, B)
}

.cuBLASsgemm <- function(A, B) {
    .Call(`_barracuda_cuBLASsgemm`, A, B)
}

.cuBLASdgemm_ABAt <- function(A, B) {
    .Call(`_barracuda_cuBLASdgemm_ABAt`, A, B)
}

.sgemm_naive <- function(A, B) {
    .Call(`_barracuda_sgemm_naive`, A, B)
}

