# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.getDeviceProps <- function(id) {
    .Call(`_barracuda_getDeviceProps`, id)
}

.dgemm <- function(A, B) {
    .Call(`_barracuda_dgemm`, A, B)
}

